services:
  visionai:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./images_with_boxes:/app/images_with_boxes
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
